# This is a basic workflow to help you get started with Actions

name: CI

env:
  CI: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Zip the resource pack
        run: cd ./unjustifiable-resouce-pack/ && zip -r result.zip . -x '*.git*' && mkdir results && mv result.zip results/result.zip

      - name: deploy to resource zip file to aws s3
        run: aws s3 sync --delete --acl public-read ./unjustifiable-resouce-pack/results/ s3://supermario1/minecraft_server/resource_pack/

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install

      - name: deploy plugin jar to aws s3
        run: aws s3 sync --delete --acl public-read ./target/JunkManServer-1.0-SNAPSHOT.jar s3://supermario1/minecraft_server/JunkManServer-1.0-SNAPSHOT.jar

      - name: tell server that we are done updating stuff so it can restart
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: whatdaheeeeeeell
